POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnZpZGFuYSIsImlkIjoiNjM4ZDIwNTc4MjU0NmM1MDlmNDg0ZGRmIiwiaWF0IjoxNjcwMTk4Njg2LCJleHAiOjE2NzAyMDIyODZ9.6A36ez7Dcc0shKKl588ZJ3SN_yQKm2SubyfWjAY2n0o

{
    "title": "Test for tokens 5",
    "author": "Daniel Vidana",
    "url": "www.toromax.com",
    "likes": 2
}