DELETE http://localhost:3003/api/blogs/638d6348cc27605d43a3ef6b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnZpZGFuYSIsImlkIjoiNjM4ZTFmZGJlYzZhMTY3Mjc4MmFhMmM3IiwiaWF0IjoxNjcwMzM4MzM4LCJleHAiOjE2NzAzNDE5Mzh9.v3b38_6TMb0iLY3rQNaYCHhbwYDNvvwnwnihkL1-SL4